version: '3'

services:

  database-host:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blueprint_repository_db
    ports:
      - "3308:3306"

  blueprint-repository:
    build: ./BlueprintRepository/
    depends_on: 
      - database-host
    ports:
      - "4000:80"